#!/usr/bin/env ruby

require 'optparse'
require 'pathname'

$LOAD_PATH << "#{Pathname.new(File.expand_path(__FILE__)).realpath.dirname}/../lib"

require 'mediacore'

options = {}

optparse = OptionParser.new do |opts|
    banner_lines = []
    banner_lines << "Usage: mediacore [options] command"
    banner_lines << "command can be init or status or import or check"
    opts.banner = banner_lines.join("\n")

    opts.on('-h', '--help', "Display this screen") do
        puts opts
        exit
    end
end

optparse.parse!

if ARGV.count != 1 then
    puts "Unknown number of arguments.  try --help"
    exit
end

mediacore_init()   if ARGV[0] == "init"
mediacore_status() if ARGV[0] == "status" 
mediacore_import() if ARGV[0] == "import"
mediacore_check()  if ARGV[0] == "check"

